# Generated by Django 5.1.6 on 2025-02-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('engine', models.CharField(max_length=50)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('horsepower', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proc', models.TextField(help_text='Advantages of the car')),
                ('cons', models.TextField(help_text='Disadvantages of the car')),
                ('create_at', models.DateTimeField(default='2025-02-15 19:46')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reviews', to='car_blog.carbrand')),
            ],
        ),
    ]
