# Generated by Django 5.1.6 on 2025-02-15 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreview',
            name='type',
            field=models.CharField(blank=True, choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Luxury', 'Luxury'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van / Minivan', 'Van / Minivan'), ('Wagon / Hatchback', 'Wagon / Hatchback')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='fuel',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
