# Generated by Django 5.1.6 on 2025-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0002_carreview_type_alter_carreview_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='brand_description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
