# Generated by Django 5.1.6 on 2025-02-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0003_carbrand_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand_description',
            field=models.TextField(blank=True),
        ),
    ]
