# Generated by Django 5.1.6 on 2025-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0004_alter_carbrand_brand_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carreview',
            old_name='horsepower',
            new_name='horsepower_max',
        ),
        migrations.AddField(
            model_name='carreview',
            name='horsepower_min',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
