# Generated by Django 5.1.6 on 2025-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0007_alter_carreview_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='carreview',
            name='fuel',
        ),
        migrations.AddField(
            model_name='carreview',
            name='fuel',
            field=models.ManyToManyField(blank=True, to='car_blog.fueltype'),
        ),
    ]
