# Generated by Django 5.1.6 on 2025-02-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0008_fueltype_remove_carreview_fuel_carreview_fuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carreview',
            old_name='proc',
            new_name='pros',
        ),
    ]
