# Generated by Django 5.1.6 on 2025-02-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0009_rename_proc_carreview_pros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrand',
            old_name='brand',
            new_name='car_brand',
        ),
    ]
