# Generated by Django 5.1.6 on 2025-02-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0011_carbrandlogo_carreviewimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrandlogo',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='car_blog.carbrand'),
        ),
    ]
