# Generated by Django 5.1.6 on 2025-03-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0012_alter_carbrandlogo_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreviewimg',
            name='car_review',
        ),
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, upload_to='brand_logos')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_logo', to='car_blog.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_imgs', models.ImageField(blank=True, upload_to='review_imgs')),
                ('car_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_review_imgs', to='car_blog.carreview')),
            ],
        ),
        migrations.DeleteModel(
            name='CarBrandLogo',
        ),
        migrations.DeleteModel(
            name='CarReviewImg',
        ),
    ]
