# Generated by Django 5.1.6 on 2025-03-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0013_remove_carreviewimg_car_review_brandlogo_reviewimgs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreview',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='carreview',
            name='pros',
        ),
        migrations.CreateModel(
            name='CarCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=150)),
                ('car_review_cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to='car_blog.carreview')),
            ],
        ),
        migrations.CreateModel(
            name='CarPros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=150)),
                ('car_review_pros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='car_blog.carreview')),
            ],
        ),
    ]
