# Generated by Django 5.1.6 on 2025-03-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0014_remove_carreview_cons_remove_carreview_pros_carcons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreview',
            name='price',
        ),
        migrations.AddField(
            model_name='carreview',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carreview',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
