# Generated by Django 4.2.19 on 2025-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0015_remove_carreview_price_carreview_price_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreview',
            name='preview_imgs',
            field=models.ImageField(blank=True, upload_to='preview_imgs'),
        ),
    ]
